fix(deps): Update npm dependencies (#36)
* npx npm-check-updates -u

* npm install

* fix "error TS2339: Property 'createPullRequest' does not exist on type 'Octokit'."

tested => https://github.com/adrienjoly/album-shelf/pull/26